default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: url_shortener_development

test:
  <<: *default
  database: url_shortener_test

production:
  <<: *default
    host: <%= ENV['URL_SHORTENER_DB_HOST'] %>
    database: <%= ENV['URL_SHORTENER_DB_NAME'] %>
    username: <%= ENV['URL_SHORTENER_DB_USER'] %>
    password: <%= ENV['URL_SHORTENER_DB_PASSWORD'] %>
